/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRecruitmentRouteImport } from './routes/_authenticated/recruitment'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedLeaveRouteImport } from './routes/_authenticated/leave'
import { Route as AuthenticatedDemoTableRouteImport } from './routes/_authenticated/demo-table'
import { Route as AuthenticatedDemoFormRouteImport } from './routes/_authenticated/demo-form'
import { Route as AuthenticatedEmployeeIndexRouteImport } from './routes/_authenticated/employee/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedCompanySetupIndexRouteImport } from './routes/_authenticated/company-setup/index'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated/attendance/index'
import { Route as AuthenticatedCompanySetupDepartmentRouteImport } from './routes/_authenticated/company-setup/department'
import { Route as AuthenticatedCompanySetupBranchRouteImport } from './routes/_authenticated/company-setup/branch'
import { Route as AuthenticatedAttendanceWorkRecordRouteImport } from './routes/_authenticated/attendance/work-record'
import { Route as AuthenticatedAttendanceMyAttendanceRouteImport } from './routes/_authenticated/attendance/my-attendance'
import { Route as AuthenticatedEmployeeEmployeeDetailsIdRouteImport } from './routes/_authenticated/employee/employee-details.$id'
import { Route as AuthenticatedEmployeeDocumentViewNameRouteImport } from './routes/_authenticated/employee/document-view.$name'
import { Route as AuthenticatedEmployeeAssignApprovalIdRouteImport } from './routes/_authenticated/employee/assign-approval.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecruitmentRoute =
  AuthenticatedRecruitmentRouteImport.update({
    id: '/recruitment',
    path: '/recruitment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaveRoute = AuthenticatedLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemoTableRoute = AuthenticatedDemoTableRouteImport.update({
  id: '/demo-table',
  path: '/demo-table',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemoFormRoute = AuthenticatedDemoFormRouteImport.update({
  id: '/demo-form',
  path: '/demo-form',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmployeeIndexRoute =
  AuthenticatedEmployeeIndexRouteImport.update({
    id: '/employee/',
    path: '/employee/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanySetupIndexRoute =
  AuthenticatedCompanySetupIndexRouteImport.update({
    id: '/company-setup/',
    path: '/company-setup/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanySetupDepartmentRoute =
  AuthenticatedCompanySetupDepartmentRouteImport.update({
    id: '/company-setup/department',
    path: '/company-setup/department',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanySetupBranchRoute =
  AuthenticatedCompanySetupBranchRouteImport.update({
    id: '/company-setup/branch',
    path: '/company-setup/branch',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttendanceWorkRecordRoute =
  AuthenticatedAttendanceWorkRecordRouteImport.update({
    id: '/attendance/work-record',
    path: '/attendance/work-record',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttendanceMyAttendanceRoute =
  AuthenticatedAttendanceMyAttendanceRouteImport.update({
    id: '/attendance/my-attendance',
    path: '/attendance/my-attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeeEmployeeDetailsIdRoute =
  AuthenticatedEmployeeEmployeeDetailsIdRouteImport.update({
    id: '/employee/employee-details/$id',
    path: '/employee/employee-details/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeeDocumentViewNameRoute =
  AuthenticatedEmployeeDocumentViewNameRouteImport.update({
    id: '/employee/document-view/$name',
    path: '/employee/document-view/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeeAssignApprovalIdRoute =
  AuthenticatedEmployeeAssignApprovalIdRouteImport.update({
    id: '/employee/assign-approval/$id',
    path: '/employee/assign-approval/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/demo-form': typeof AuthenticatedDemoFormRoute
  '/demo-table': typeof AuthenticatedDemoTableRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/recruitment': typeof AuthenticatedRecruitmentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/attendance/my-attendance': typeof AuthenticatedAttendanceMyAttendanceRoute
  '/attendance/work-record': typeof AuthenticatedAttendanceWorkRecordRoute
  '/company-setup/branch': typeof AuthenticatedCompanySetupBranchRoute
  '/company-setup/department': typeof AuthenticatedCompanySetupDepartmentRoute
  '/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/company-setup/': typeof AuthenticatedCompanySetupIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/employee/': typeof AuthenticatedEmployeeIndexRoute
  '/employee/assign-approval/$id': typeof AuthenticatedEmployeeAssignApprovalIdRoute
  '/employee/document-view/$name': typeof AuthenticatedEmployeeDocumentViewNameRoute
  '/employee/employee-details/$id': typeof AuthenticatedEmployeeEmployeeDetailsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/demo-form': typeof AuthenticatedDemoFormRoute
  '/demo-table': typeof AuthenticatedDemoTableRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/recruitment': typeof AuthenticatedRecruitmentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/attendance/my-attendance': typeof AuthenticatedAttendanceMyAttendanceRoute
  '/attendance/work-record': typeof AuthenticatedAttendanceWorkRecordRoute
  '/company-setup/branch': typeof AuthenticatedCompanySetupBranchRoute
  '/company-setup/department': typeof AuthenticatedCompanySetupDepartmentRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/company-setup': typeof AuthenticatedCompanySetupIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/employee': typeof AuthenticatedEmployeeIndexRoute
  '/employee/assign-approval/$id': typeof AuthenticatedEmployeeAssignApprovalIdRoute
  '/employee/document-view/$name': typeof AuthenticatedEmployeeDocumentViewNameRoute
  '/employee/employee-details/$id': typeof AuthenticatedEmployeeEmployeeDetailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/demo-form': typeof AuthenticatedDemoFormRoute
  '/_authenticated/demo-table': typeof AuthenticatedDemoTableRoute
  '/_authenticated/leave': typeof AuthenticatedLeaveRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/recruitment': typeof AuthenticatedRecruitmentRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/attendance/my-attendance': typeof AuthenticatedAttendanceMyAttendanceRoute
  '/_authenticated/attendance/work-record': typeof AuthenticatedAttendanceWorkRecordRoute
  '/_authenticated/company-setup/branch': typeof AuthenticatedCompanySetupBranchRoute
  '/_authenticated/company-setup/department': typeof AuthenticatedCompanySetupDepartmentRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/company-setup/': typeof AuthenticatedCompanySetupIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/employee/': typeof AuthenticatedEmployeeIndexRoute
  '/_authenticated/employee/assign-approval/$id': typeof AuthenticatedEmployeeAssignApprovalIdRoute
  '/_authenticated/employee/document-view/$name': typeof AuthenticatedEmployeeDocumentViewNameRoute
  '/_authenticated/employee/employee-details/$id': typeof AuthenticatedEmployeeEmployeeDetailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/demo-form'
    | '/demo-table'
    | '/leave'
    | '/payroll'
    | '/recruitment'
    | '/settings'
    | '/tasks'
    | '/attendance/my-attendance'
    | '/attendance/work-record'
    | '/company-setup/branch'
    | '/company-setup/department'
    | '/attendance/'
    | '/company-setup/'
    | '/dashboard/'
    | '/employee/'
    | '/employee/assign-approval/$id'
    | '/employee/document-view/$name'
    | '/employee/employee-details/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/demo-form'
    | '/demo-table'
    | '/leave'
    | '/payroll'
    | '/recruitment'
    | '/settings'
    | '/tasks'
    | '/attendance/my-attendance'
    | '/attendance/work-record'
    | '/company-setup/branch'
    | '/company-setup/department'
    | '/attendance'
    | '/company-setup'
    | '/dashboard'
    | '/employee'
    | '/employee/assign-approval/$id'
    | '/employee/document-view/$name'
    | '/employee/employee-details/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/unauthorized'
    | '/_authenticated/demo-form'
    | '/_authenticated/demo-table'
    | '/_authenticated/leave'
    | '/_authenticated/payroll'
    | '/_authenticated/recruitment'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/attendance/my-attendance'
    | '/_authenticated/attendance/work-record'
    | '/_authenticated/company-setup/branch'
    | '/_authenticated/company-setup/department'
    | '/_authenticated/attendance/'
    | '/_authenticated/company-setup/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/employee/'
    | '/_authenticated/employee/assign-approval/$id'
    | '/_authenticated/employee/document-view/$name'
    | '/_authenticated/employee/employee-details/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recruitment': {
      id: '/_authenticated/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof AuthenticatedRecruitmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave': {
      id: '/_authenticated/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedLeaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo-table': {
      id: '/_authenticated/demo-table'
      path: '/demo-table'
      fullPath: '/demo-table'
      preLoaderRoute: typeof AuthenticatedDemoTableRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo-form': {
      id: '/_authenticated/demo-form'
      path: '/demo-form'
      fullPath: '/demo-form'
      preLoaderRoute: typeof AuthenticatedDemoFormRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employee/': {
      id: '/_authenticated/employee/'
      path: '/employee'
      fullPath: '/employee/'
      preLoaderRoute: typeof AuthenticatedEmployeeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company-setup/': {
      id: '/_authenticated/company-setup/'
      path: '/company-setup'
      fullPath: '/company-setup/'
      preLoaderRoute: typeof AuthenticatedCompanySetupIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company-setup/department': {
      id: '/_authenticated/company-setup/department'
      path: '/company-setup/department'
      fullPath: '/company-setup/department'
      preLoaderRoute: typeof AuthenticatedCompanySetupDepartmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company-setup/branch': {
      id: '/_authenticated/company-setup/branch'
      path: '/company-setup/branch'
      fullPath: '/company-setup/branch'
      preLoaderRoute: typeof AuthenticatedCompanySetupBranchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance/work-record': {
      id: '/_authenticated/attendance/work-record'
      path: '/attendance/work-record'
      fullPath: '/attendance/work-record'
      preLoaderRoute: typeof AuthenticatedAttendanceWorkRecordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance/my-attendance': {
      id: '/_authenticated/attendance/my-attendance'
      path: '/attendance/my-attendance'
      fullPath: '/attendance/my-attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceMyAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employee/employee-details/$id': {
      id: '/_authenticated/employee/employee-details/$id'
      path: '/employee/employee-details/$id'
      fullPath: '/employee/employee-details/$id'
      preLoaderRoute: typeof AuthenticatedEmployeeEmployeeDetailsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employee/document-view/$name': {
      id: '/_authenticated/employee/document-view/$name'
      path: '/employee/document-view/$name'
      fullPath: '/employee/document-view/$name'
      preLoaderRoute: typeof AuthenticatedEmployeeDocumentViewNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employee/assign-approval/$id': {
      id: '/_authenticated/employee/assign-approval/$id'
      path: '/employee/assign-approval/$id'
      fullPath: '/employee/assign-approval/$id'
      preLoaderRoute: typeof AuthenticatedEmployeeAssignApprovalIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDemoFormRoute: typeof AuthenticatedDemoFormRoute
  AuthenticatedDemoTableRoute: typeof AuthenticatedDemoTableRoute
  AuthenticatedLeaveRoute: typeof AuthenticatedLeaveRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedRecruitmentRoute: typeof AuthenticatedRecruitmentRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedAttendanceMyAttendanceRoute: typeof AuthenticatedAttendanceMyAttendanceRoute
  AuthenticatedAttendanceWorkRecordRoute: typeof AuthenticatedAttendanceWorkRecordRoute
  AuthenticatedCompanySetupBranchRoute: typeof AuthenticatedCompanySetupBranchRoute
  AuthenticatedCompanySetupDepartmentRoute: typeof AuthenticatedCompanySetupDepartmentRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
  AuthenticatedCompanySetupIndexRoute: typeof AuthenticatedCompanySetupIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedEmployeeIndexRoute: typeof AuthenticatedEmployeeIndexRoute
  AuthenticatedEmployeeAssignApprovalIdRoute: typeof AuthenticatedEmployeeAssignApprovalIdRoute
  AuthenticatedEmployeeDocumentViewNameRoute: typeof AuthenticatedEmployeeDocumentViewNameRoute
  AuthenticatedEmployeeEmployeeDetailsIdRoute: typeof AuthenticatedEmployeeEmployeeDetailsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDemoFormRoute: AuthenticatedDemoFormRoute,
  AuthenticatedDemoTableRoute: AuthenticatedDemoTableRoute,
  AuthenticatedLeaveRoute: AuthenticatedLeaveRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedRecruitmentRoute: AuthenticatedRecruitmentRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedAttendanceMyAttendanceRoute:
    AuthenticatedAttendanceMyAttendanceRoute,
  AuthenticatedAttendanceWorkRecordRoute:
    AuthenticatedAttendanceWorkRecordRoute,
  AuthenticatedCompanySetupBranchRoute: AuthenticatedCompanySetupBranchRoute,
  AuthenticatedCompanySetupDepartmentRoute:
    AuthenticatedCompanySetupDepartmentRoute,
  AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  AuthenticatedCompanySetupIndexRoute: AuthenticatedCompanySetupIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedEmployeeIndexRoute: AuthenticatedEmployeeIndexRoute,
  AuthenticatedEmployeeAssignApprovalIdRoute:
    AuthenticatedEmployeeAssignApprovalIdRoute,
  AuthenticatedEmployeeDocumentViewNameRoute:
    AuthenticatedEmployeeDocumentViewNameRoute,
  AuthenticatedEmployeeEmployeeDetailsIdRoute:
    AuthenticatedEmployeeEmployeeDetailsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
